In [7]:
import numpy as np

In [9]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
mat2D = np.array([[10,20,30,40] , [50,60,70,80] , [90,100,110,120]])

In [11]:
print(f"Nilai mat1D :\n{mat1D}")
print(f"Nilai mat2D :\n{mat2D}")

Nilai mat1D :
[1 2 3 4 5 6 7 8 9]
Nilai mat2D :
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [17]:
print(mat1D[1]) #2
print(mat2D[1]) # [50, 60, 70, 80]
print(mat2D[1][2]) #70
print(f"mat1D ditambah dengan 10 :\n{mat1D + 10}")
print(f"mat2D ditambah dengan 2:\n{mat2D + 2}")

2
[50 60 70 80]
70
mat1D ditambah dengan 10 :
[11 12 13 14 15 16 17 18 19]
mat2D ditambah dengan 2:
[[ 12  22  32  42]
 [ 52  62  72  82]
 [ 92 102 112 122]]


In [23]:
print(mat1D.shape)
print(mat1D.size)
print(f"Bentuk dari mat2D : {mat2D.shape}")
print(f"Ukuran dari mat2D : {mat2D.size}")

(9,)
9
Bentuk dari mat2D : (3, 4)
Ukuran dari mat2D : 12


In [79]:
#Matriks Special (Matriks Zero)

mZero = np.zeros ((4,4))
mOne = np.ones ((3,3))
mIdentity = np.eye((3))
mFull = np.full((3,4) , 10)
mRand1D = np.random.rand(5)  #1D
mRand2D = np.random.rand(3,4)
mRandInt1D = np.random.randint(1,100, size=8)
mRandInt2D = np.random.randint(1,100, size=(3,3))

In [83]:
print(f"mZero :\n {mZero}")
print(f"mOne :\n{mOne}")
print(f"mIdentity :\n{mIdentity}")
print(f"mFull :\n{mFull}")
print(f"mRand :\n{mRand1D}")
print(f"mRand2D :\n {mRand2D}")
print(f"mRandInt1D : \n{mRandInt1D}")
print(f"mRandInt2D :\n{mRandInt2D}")

mZero :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
mOne :
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
mIdentity :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
mFull :
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
mRand :
[0.95918604 0.12877429 0.37923966 0.31671819 0.87316528]
mRand2D :
 [[0.20240035 0.45963836 0.28668981 0.07012175]
 [0.69280131 0.39936585 0.17211094 0.3221582 ]
 [0.33699556 0.87311766 0.51615013 0.2840926 ]]
mRandInt1D : 
[67 80 80 33 84 11 21 77]
mRandInt2D :
[[83 60 28]
 [40 32 70]
 [29 35 29]]


In [91]:
#Operasi Aritmatika

x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

r1 = np.add(x,y)
r2 = np.dot(x,y)

print(f"Hasil Penjumlahan x dan y : {r1}")
print(f"Hasil dari dot product : {r2}")

Hasil Penjumlahan x dan y : [ 7  9 11 13 15]
Hasil dari dot product : 130


In [109]:
#Fugsi dasat Statistika
nilaiPrograming = np.array([100,90,90, 50,80,60,50,])
print(f"Nilai Pemrtogtam :{nilaiPrograming}")
print(f"Nilai yang paling rendah : {np.min(nilaiPrograming)} ")
print(f"Nilai yang paling Tinggi :{np.max(nilaiPrograming)}")
print(f"Nilai Rata - Rata: {np.mean(nilaiPrograming)}")
print(f"Nilai Rata - Rata: {np.mean(nilaiPrograming)}")

Nilai Pemrtogtam :[100  90  90  50  80  60  50]
Nilai yang paling rendah : 50 
Nilai yang paling Tinggi :100
Nilai Rata - Rata: 74.28571428571429


In [111]:
#Filtering
lulus = nilaiPrograming[nilaiPrograming > 50]

print(f"Daftar niai yang lulus : {lulus}")

Daftar niai yang lulus : [100  90  90  80  60]


In [119]:
print(f"Jumlah yang lulus : {lulus.size}")

Jumlah yang lulus : 5


<b1>Contoh Kasus Data set </b1>
Buatlah data set sebanyak 10.000 untuk proses klasifikasi nasabah kartu kredit

<ol>
    <li>Usia: 17 - 60</li>
    <li> Gender: L/P</li>
    <li>Gaji: 1jt - 3jt, 3jt - 5jt, 5jt - 10jt</li>
    <li>Jumlah Anak : 0 - 6</li>
    
</ol>

In [170]:
import numpy as np
import pandas as pd

n_data = 10000
usia = np.random.randint(17,61, size=n_data)
gender = np.random.choice(['L' , 'P'], size=n_data)
gaji = np.random.choice(['1-3jt', '3-5jt', '5-10jt'])
anak =  np.random.randint(0,7, size=n_data)

df = pd.DataFrame ({
    'Usia' : usia,
    'Gender' : gender,
    'Gaji' : gaji,
    'Jumlah Anak' : anak
})

df.to_csv('data_calon_nasabah.csv')

print(df.info())
print(df.head())
print(df.shape)
print(df.size)
print(f"Usia Termuda : {df['Usia'].min()}") #Tampilkan Usia calon nasabah yang paling muda
print(f"Usia Tertua : {df['Usia'].max()}") #Tampilkan Usia calon nasabah yang paling tua
#print(f"Gaji Rata-Rata : {df['Gaji'].mean()}")#Tampilkan Gaji Rata-Rata
jLaki = df[df['Gender'] == 'L'] #Tampilkan berapa jumlah Laki-Laki
print(f"Jumlah calon nasabah lak-laki : {jLaki.size/4}")
print(f"Jumlah calon nasabah laki-laki : {jLaki['Gender'].size}")
jPerempuan = df[df['Gender'] == 'P'] #Tampilkan berapa jumlah Perempuan
print(f"Jumlah calon nasabah Perempuan : {jPerempuan.size/4}")
print(f"Jumlah calon nasabah Perempuan : {jPerempuan['Gender'].size}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Usia         10000 non-null  int32 
 1   Gender       10000 non-null  object
 2   Gaji         10000 non-null  object
 3   Jumlah Anak  10000 non-null  int32 
dtypes: int32(2), object(2)
memory usage: 234.5+ KB
None
   Usia Gender    Gaji  Jumlah Anak
0    53      P  5-10jt            2
1    37      P  5-10jt            2
2    40      P  5-10jt            2
3    36      L  5-10jt            3
4    56      L  5-10jt            1
(10000, 4)
40000
Usia Termuda : 17
Usia Tertua : 60
Jumlah calon nasabah lak-laki : 5047.0
Jumlah calon nasabah laki-laki : 5047
Jumlah calon nasabah Perempuan : 4953.0
Jumlah calon nasabah Perempuan : 4953
